remove db init for testconteiners
Flexiana/framework pull request #157
Opened 2021-11-18 11:42 UTC by jehaby

2021-11-18 11:47 UTC, g-krisztian requested changes

2021-11-18 11:47 UTC, g-krisztian commented on src/framework/db/core.clj
>          db-instance (case (:deployment db-spec)
maybe it should be removed here, and advice to use docker-postgres! separately, on app startup.

2021-11-18 16:13 UTC, jehaby commented on examples/cli-chat/test/cli_chat_fixture.clj
> +                  #(-> % db/docker-postgres! db/start))]
Changed, but I'm not sure this is better :)

2021-11-18 16:13 UTC, jehaby commented on src/framework/db/core.clj
> +      (jdbc/execute! (dissoc pg-config :dbname) init-sql))
I agree, removed it

2021-11-22 09:35 UTC, g-krisztian approved these changes

2021-11-22 09:45 UTC, merged