update yougthous config
Flexiana/framework pull request #194
Opened 2022-02-01 12:34 UTC by jehaby

## Title: 

### Description
A brief summary of the changes including a description of the new behaviour or the fixed bug.

### Tester info
A brief description of any steps needed to demonstrate the new functionality or show the bug is fixed

2022-02-01 12:42 UTC, g-krisztian reviewed
Looks good, pls update framework's version number too

2022-02-02 13:29 UTC, g-krisztian approved these changes

2022-02-02 16:43 UTC, soulflyer requested changes
Looks good, just needs the passwords to match so the examples work as per their read-me files

2022-02-02 16:43 UTC, soulflyer commented on examples/cli-chat/docker-compose.yml
> +      - POSTGRES_PASSWORD=dev
and here

2022-02-02 16:43 UTC, soulflyer commented on examples/controllers/docker-compose.yml
> +      - POSTGRES_PASSWORD=dev
and here

2022-02-03 15:37 UTC, merged