Add some simplifications at startup
Flexiana/framework pull request #38
Opened 2021-02-10 17:04 UTC by ianffcs

Adding some suggestions for startup simplification.

2021-02-10 18:42 UTC, ianffcs commented
Trying to simplify data-flow from configuration to application usage, not needed but suggesting some ideas.

2021-02-11 11:23 UTC, narocath approved these changes

2021-02-11 12:08 UTC, PiotrKurnik approved these changes

2021-02-11 12:23 UTC, g-krisztian requested changes

2021-02-11 12:23 UTC, g-krisztian commented on src/framework/components/core.clj
> +        component/start)))
Why not `(-> (load-env) system component/start)`?

2021-02-11 12:23 UTC, g-krisztian commented on src/framework/db/migrations/core.clj
> +  [fpath namespace]
pls add typehint for namespace parameter

2021-02-11 13:51 UTC, g-krisztian approved these changes

2021-02-11 15:43 UTC, merged