Dev/password hashing
Flexiana/framework pull request #48
Opened 2021-02-17 14:24 UTC by brahayan-dev

Hi team, this branch is about **Password hashing functionality** (https://3.basecamp.com/4984255/buckets/20801355/todos/3460984539)

2021-02-17 16:07 UTC, g-krisztian requested changes

2021-02-17 16:07 UTC, g-krisztian commented on src/framework/auth/hash.clj
> +(defmethod check :bcrypt [_state password encrypted]
Can be the unused parameter changed to `_`?

2021-02-17 16:07 UTC, g-krisztian commented on test/framework/auth/hash_test.clj
> +    (println encrypted)
```suggestion
```

2021-02-17 20:45 UTC, brahayan-dev commented on test/framework/auth/hash_test.clj
> +    (println encrypted)
So thanks, I forgot it

2021-02-18 08:07 UTC, g-krisztian approved these changes

2021-02-26 12:34 UTC, PiotrKurnik approved these changes

2021-02-26 18:14 UTC, merged